/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho_desktop.view;

import trabalho_desktop.controller.DBController;
import trabalho_desktop.controller.DoctorController;
import trabalho_desktop.model.Doctor;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import trabalho_desktop.exceptions.CreateException;
import trabalho_desktop.exceptions.CrmLengthException;
import trabalho_desktop.exceptions.DeleteException;
import trabalho_desktop.exceptions.EditException;
import trabalho_desktop.exceptions.RgLengthException;
import trabalho_desktop.exceptions.StateException;

/**
 *
 * @author erick
 */
public class DoctorView extends javax.swing.JFrame {
    DBController dbController;
    DoctorController doctorController;
    /**
     * Creates new form DoctorView
     */
    public DoctorView() {
        initComponents();
    }
    
    public DoctorView(DBController dbController){
        this.dbController = dbController;
        this.doctorController = new DoctorController(dbController.getConnection());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        crm = new javax.swing.JLabel();
        crmNumberField = new javax.swing.JTextField();
        crmNumber = new javax.swing.JLabel();
        crmStateField = new javax.swing.JTextField();
        crmState = new javax.swing.JLabel();
        rg = new javax.swing.JLabel();
        rgField = new javax.swing.JTextField();
        espec = new javax.swing.JLabel();
        especField = new javax.swing.JTextField();
        closeBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        addDoctor = new javax.swing.JButton();
        searchDoctor = new javax.swing.JButton();
        searchAllDoctors = new javax.swing.JButton();
        deleteDoctor = new javax.swing.JButton();
        editDoctor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        name.setText("Nome:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        crm.setText("Dados profissionais");

        crmNumber.setText("Número:");

        crmState.setText("Estado:");

        rg.setText("RG:");

        rgField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgFieldActionPerformed(evt);
            }
        });

        espec.setText("Especialização:");

        especField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especFieldActionPerformed(evt);
            }
        });

        closeBtn.setText("Sair");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Limpar");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        addDoctor.setText("Criar médico");
        addDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorActionPerformed(evt);
            }
        });

        searchDoctor.setText("Consultar pelo RG");
        searchDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDoctorActionPerformed(evt);
            }
        });

        searchAllDoctors.setText("Ver todos os médicos");
        searchAllDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAllDoctorsActionPerformed(evt);
            }
        });

        deleteDoctor.setText("Remover pelo RG");
        deleteDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDoctorActionPerformed(evt);
            }
        });

        editDoctor.setText("Editar pelo RG");
        editDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchAllDoctors)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(crmNumber)
                                .addGap(18, 18, 18)
                                .addComponent(crmNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(crmState)
                                .addGap(18, 18, 18)
                                .addComponent(crmStateField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(crm)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name)
                                    .addComponent(rg))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rgField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(espec)
                                .addGap(18, 18, 18)
                                .addComponent(especField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchDoctor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteDoctor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editDoctor)))
                        .addGap(0, 77, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rg)
                    .addComponent(rgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(crm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crmNumber)
                    .addComponent(crmNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crmState)
                    .addComponent(crmStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espec)
                    .addComponent(especField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDoctor)
                    .addComponent(searchDoctor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteDoctor)
                    .addComponent(editDoctor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBtn)
                    .addComponent(clearBtn)
                    .addComponent(searchAllDoctors))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void rgFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgFieldActionPerformed

    private void especFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especFieldActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
    close();        // TODO add your handling code here:
    }//GEN-LAST:event_closeBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
    clear();        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtnActionPerformed

    private void addDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorActionPerformed
        Doctor doctor = new Doctor();
        try{
            doctor.setId(0);
            doctor.setName(nameField.getText());
            doctor.setRg(rgField.getText());
            doctor.setRole(1);
            doctor.getCrm().setNum(Integer.parseInt(crmNumberField.getText()));
            doctor.getCrm().setEstado(crmStateField.getText());
            doctor.setEspec(especField.getText());
            ArrayList<Doctor> doctorList = dbController.getDoctorList();
            doctorList = doctorController.createDoctor(doctor, doctorList);
            dbController.setDoctorList(doctorList);
            JOptionPane.showMessageDialog(null, "Usuário criado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            clear();
        }catch(RgLengthException rle){
            JOptionPane.showMessageDialog(null, rle.getError(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }catch(CrmLengthException cle){
            JOptionPane.showMessageDialog(null, cle.getError(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }catch(StateException cse){
            JOptionPane.showMessageDialog(null, cse.getError(), "Erro!", JOptionPane.ERROR_MESSAGE);// TODO add your handling code here:
        } catch (CreateException cex) {
            JOptionPane.showMessageDialog(null, cex.getError(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addDoctorActionPerformed

    private void searchDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDoctorActionPerformed
    searchByRg();    // TODO add your handling code here:
    }//GEN-LAST:event_searchDoctorActionPerformed

    private void searchAllDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAllDoctorsActionPerformed
        new DoctorTableView(dbController).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_searchAllDoctorsActionPerformed

    private void deleteDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDoctorActionPerformed
    try{
        ArrayList<Doctor> doctorList = dbController.getDoctorList();
        doctorList = doctorController.deleteDoctor(doctorController.searchByRg(rgField.getText(), doctorList), doctorList);
        dbController.setDoctorList(doctorList);
        clear();
        rgField.requestFocus();
        JOptionPane.showMessageDialog(null, "Usuário removido com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
    } catch(RgLengthException rle){
        JOptionPane.showMessageDialog(null, rle.getError(), "Erro!", JOptionPane.ERROR_MESSAGE);
    }   catch (DeleteException dex) {
            JOptionPane.showMessageDialog(null, dex.getError(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_deleteDoctorActionPerformed

    private void editDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDoctorActionPerformed
        Doctor doctorEdited = new Doctor();
        ArrayList<Doctor> doctorList = dbController.getDoctorList();
        try{
            doctorEdited.setId(0);
            doctorEdited.setName(nameField.getText());
            doctorEdited.setRg(rgField.getText());
            doctorEdited.setRole(1);
            doctorEdited.getCrm().setNum(Integer.parseInt(crmNumberField.getText()));
            doctorEdited.getCrm().setEstado(crmStateField.getText());
            doctorEdited.setEspec(especField.getText());
            dbController.setDoctorList(doctorController.editDoctor(doctorEdited, doctorList));
            JOptionPane.showMessageDialog(null, "Usuário editado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        }catch(RgLengthException rle){
            JOptionPane.showMessageDialog(null, rle.getError(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }catch(CrmLengthException cle){
            JOptionPane.showMessageDialog(null, cle.getError(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }catch(StateException ste){
            JOptionPane.showMessageDialog(null, ste.getError(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }catch(EditException eex){
            JOptionPane.showMessageDialog(null, eex.getError(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_editDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorView().setVisible(true);
            }
        });
    }
    
    public void searchByRg(){
        try{
           Doctor doctor = doctorController.searchByRg(rgField.getText(), dbController.getDoctorList());
           if(doctor == null){
            JOptionPane.showMessageDialog(null, "Paciente não encontrado!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
           }
           nameField.setText(doctor.getName());
           crmNumberField.setText(Integer.toString(doctor.getCrm().getNum()));
           crmStateField.setText(doctor.getCrm().getEstado());
           especField.setText(doctor.getEspec());
        }catch(RgLengthException rle){
            JOptionPane.showMessageDialog(null, rle.getError(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void close(){
        int resp = JOptionPane.showConfirmDialog(
                    null,
                    "Deseja sair?",
                    "Saida",
                    JOptionPane.YES_NO_OPTION
                  );
        if(resp == 0){
            dispose();
        }
    }
    
     public void clear(){
        nameField.setText("");
        rgField.setText("");
        crmNumberField.setText("");
        crmStateField.setText("");
        especField.setText("");
        nameField.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoctor;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel crm;
    private javax.swing.JLabel crmNumber;
    private javax.swing.JTextField crmNumberField;
    private javax.swing.JLabel crmState;
    private javax.swing.JTextField crmStateField;
    private javax.swing.JButton deleteDoctor;
    private javax.swing.JButton editDoctor;
    private javax.swing.JLabel espec;
    private javax.swing.JTextField especField;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel rg;
    private javax.swing.JTextField rgField;
    private javax.swing.JButton searchAllDoctors;
    private javax.swing.JButton searchDoctor;
    // End of variables declaration//GEN-END:variables
}
